//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class antecd_quirur_traumati
    {
        public int i_pk_quirurgicos_traumati { get; set; }
        public string vc_fracturas { get; set; }
        public string vc_donde { get; set; }
        public Nullable<System.DateTime> dt_fractura { get; set; }
        public string vc_cirugias { get; set; }
        public string vc_cirugias_donde { get; set; }
        public Nullable<System.DateTime> dt_cirugia { get; set; }
        public string vc_acci_no_laborales { get; set; }
        public string vc_acci_laborales { get; set; }
        public int i_pk_estado { get; set; }
    }
}
