//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_ExpMedico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_ExpMedico()
        {
            this.Exp_Diagnostico = new HashSet<Exp_Diagnostico>();
        }
    
        public int i_PK_ExpMedico { get; set; }
        public Nullable<int> i_FK_idFuncionario { get; set; }
        public Nullable<int> i_FK_idUsuExterno { get; set; }
        public System.DateTime d_ExpMedico { get; set; }
        public int i_fk_GineObstetricos { get; set; }
        public int i_fk_HereFamiliar { get; set; }
        public int i_fk_QuirTrauma { get; set; }
        public int i_fk_AntPatoPersonales { get; set; }
        public bool b_Estado { get; set; }
    
        public virtual CM_UsuarioExterno CM_UsuarioExterno { get; set; }
        public virtual Exp_AnteQuirurTrauma Exp_AnteQuirurTrauma { get; set; }
        public virtual Exp_AntPersoPatolog Exp_AntPersoPatolog { get; set; }
        public virtual Exp_GinecoObstreticos Exp_GinecoObstreticos { get; set; }
        public virtual Exp_HeredoFamiliar Exp_HeredoFamiliar { get; set; }
        public virtual Funcionarios Funcionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exp_Diagnostico> Exp_Diagnostico { get; set; }
    }
}
