//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_HorarioServicio
    {
        public int i_Pk_idHoraServicio { get; set; }
        public int i_Fk_idMedico { get; set; }
        public System.TimeSpan t_HoraInicio { get; set; }
        public System.TimeSpan t_HoraFinal { get; set; }
        public string vc_DiaServicio { get; set; }
    
        public virtual CM_Medico CM_Medico { get; set; }
    }
}
