//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ci_Cita
    {
        public int i_PK_id_cita { get; set; }
        public string vc_id_usuario { get; set; }
        public string vc_id_medico { get; set; }
        public System.DateTime dt_hora_inicio { get; set; }
        public System.DateTime dt_hora_fin { get; set; }
    
        public virtual Med_Medico Med_Medico { get; set; }
        public virtual Us_Usuario Us_Usuario { get; set; }
    }
}
