//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int i_pk_cita { get; set; }
        public int i_fk_usuario { get; set; }
        public int i_fk_medico { get; set; }
        public System.DateTime dt_hora_inicio { get; set; }
        public System.DateTime dt_hora_fin { get; set; }
        public int i_pk_estado { get; set; }
    }
}
