//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_CAT_ANTECEDENTES_PER_PATOLOGICOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CM_CAT_ANTECEDENTES_PER_PATOLOGICOS()
        {
            this.Exp_Medico = new HashSet<Exp_Medico>();
        }
    
        public int i_pk_antecents_patologicos { get; set; }
        public string vc_piel { get; set; }
        public string vc_aparato_digestivo { get; set; }
        public string vc_aparato_gene_urinario { get; set; }
        public string vc_sist_nervioso { get; set; }
        public string vc_sist_musc_esquele { get; set; }
        public string vc_sistem_endocri { get; set; }
        public string vc_sistm_cardio { get; set; }
        public string vc_alergias { get; set; }
        public string vc_Problems_psicolo { get; set; }
        public int i_fk_estado { get; set; }
    
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exp_Medico> Exp_Medico { get; set; }
    }
}
