//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_Medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CM_Medico()
        {
            this.Cat_HorarioServicio = new HashSet<Cat_HorarioServicio>();
            this.CM_Cita = new HashSet<CM_Cita>();
            this.Exp_Diagnostico = new HashSet<Exp_Diagnostico>();
        }
    
        public int i_Pk_idMedico { get; set; }
        public int i_Fk_Funcionario { get; set; }
        public int i_Fk_idEspecialidad { get; set; }
        public Nullable<int> i_Fk_idExcHorario { get; set; }
        public bool b_Estado { get; set; }
    
        public virtual Cat_Especialidad Cat_Especialidad { get; set; }
        public virtual Cat_ExcepHorario Cat_ExcepHorario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_HorarioServicio> Cat_HorarioServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CM_Cita> CM_Cita { get; set; }
        public virtual Funcionarios Funcionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exp_Diagnostico> Exp_Diagnostico { get; set; }
    }
}
