//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_UsuarioExterno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CM_UsuarioExterno()
        {
            this.Cat_ExpMedico = new HashSet<Cat_ExpMedico>();
            this.CM_Cita = new HashSet<CM_Cita>();
        }
    
        public int i_Pk_idUsuExterno { get; set; }
        public string vc_Cedula { get; set; }
        public string vc_Nombre { get; set; }
        public string vc_PriApellido { get; set; }
        public string vc_SegApellido { get; set; }
        public string vc_Telefono { get; set; }
        public string vc_Movil { get; set; }
        public string vc_Sexo { get; set; }
        public string vc_Email { get; set; }
        public string vc_Empresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_ExpMedico> Cat_ExpMedico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CM_Cita> CM_Cita { get; set; }
    }
}
