//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostico
    {
        public int i_PK_Diagnostico { get; set; }
        public int i_FK_Expediente { get; set; }
        public string vc_Descripcion { get; set; }
        public System.DateTime dt_diagnostico { get; set; }
    
        public virtual Exp_Medico Exp_Medico { get; set; }
    }
}
