//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enc_Comprobante
    {
        public int i_id_comprobante { get; set; }
        public System.DateTime date_comprobante { get; set; }
        public string id_usuario { get; set; }
    }
}
