//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Examen_Diagnostico
    {
        public int id_PK_examen_medico { get; set; }
        public string vc_diagnostico { get; set; }
        public string vc_id_usuario { get; set; }
    
        public virtual Us_Usuario Us_Usuario { get; set; }
    }
}
