//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exp_GinecoObstreticos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exp_GinecoObstreticos()
        {
            this.Cat_ExpMedico = new HashSet<Cat_ExpMedico>();
        }
    
        public int i_Pk_idGinObste { get; set; }
        public string vc_Menarca { get; set; }
        public string vc_Fur { get; set; }
        public Nullable<bool> b_RelacionesSexuales { get; set; }
        public Nullable<bool> b_Planificar { get; set; }
        public Nullable<bool> b_Ritmo { get; set; }
        public string vc_Metodo { get; set; }
        public string vc_Duracion { get; set; }
        public Nullable<bool> b_PartosEutocicos { get; set; }
        public Nullable<bool> b_Forceps { get; set; }
        public Nullable<bool> b_Cesareas { get; set; }
        public Nullable<bool> b_Flujos { get; set; }
        public string vc_SangradoAnormal { get; set; }
        public Nullable<bool> b_Pap { get; set; }
        public Nullable<System.DateTime> d_pap { get; set; }
        public string vc_resultado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_ExpMedico> Cat_ExpMedico { get; set; }
    }
}
