//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exp_AntPersoPatolog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exp_AntPersoPatolog()
        {
            this.Cat_ExpMedico = new HashSet<Cat_ExpMedico>();
        }
    
        public int i_Pk_AntPatologicos { get; set; }
        public string vc_Piel { get; set; }
        public string vc_ApaDigestivo { get; set; }
        public string vc_ApaGeneUrinario { get; set; }
        public string vc_SisNervioso { get; set; }
        public string vc_SisMuscEsquele { get; set; }
        public string vc_SisEndocri { get; set; }
        public string vc_SisCardio { get; set; }
        public string vc_Alergias { get; set; }
        public string vc_ProblemPsicolo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_ExpMedico> Cat_ExpMedico { get; set; }
    }
}
