//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exp_Medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exp_Medico()
        {
            this.Diagnostico = new HashSet<Diagnostico>();
        }
    
        public int i_PK_ExpMedico { get; set; }
        public int i_FK_id_usuario { get; set; }
        public int i_fk_id_medico { get; set; }
        public System.DateTime dt_expMedico { get; set; }
        public int i_fk_estado { get; set; }
        public Nullable<int> i_fk_gineco_obstetricos { get; set; }
        public int i_fk_heredo_famili { get; set; }
        public int i_fk_quirurgicos_traumati { get; set; }
        public int i_fk_antecents_patologicos_personales { get; set; }
        public int i_fk_antecents_patologicos { get; set; }
    
        public virtual CM_CAT_ANTECEDENTES_PER_PATOLOGICOS CM_CAT_ANTECEDENTES_PER_PATOLOGICOS { get; set; }
        public virtual CM_EXP_ANTECEDENTES_QUIRURGICOS_TRAUMATICOS CM_EXP_ANTECEDENTES_QUIRURGICOS_TRAUMATICOS { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Heredo_familiar Heredo_familiar { get; set; }
        public virtual Heredo_familiar Heredo_familiar1 { get; set; }
        public virtual Med_Medico Med_Medico { get; set; }
        public virtual Us_UsuarioExterno Us_UsuarioExterno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnostico> Diagnostico { get; set; }
    }
}
