//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exp_Expediente
    {
        public int i_PK_expediente { get; set; }
        public string vc_id_puesto { get; set; }
        public string vc_id_usuario { get; set; }
        public System.DateTime dt_fecha { get; set; }
        public string ch_pract_deporte { get; set; }
        public string vc_deporte { get; set; }
        public string ch_fuma { get; set; }
        public string vc_cantidad { get; set; }
        public Nullable<System.DateTime> dt_inicio_fumado { get; set; }
        public string ch_licor { get; set; }
        public string vc_frecuencia { get; set; }
        public Nullable<int> i_cantidad { get; set; }
        public string ch_hijos { get; set; }
        public Nullable<int> i_cant_hijos { get; set; }
        public string vc_clinica_abscrita { get; set; }
    
        public virtual Emp_Puesto Emp_Puesto { get; set; }
        public virtual Us_Usuario Us_Usuario { get; set; }
    }
}
