//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exp_Diagnostico
    {
        public int i_PK_Diagnostico { get; set; }
        public int i_fk_idMedico { get; set; }
        public int i_fk_idExpMedico { get; set; }
        public string vc_Descripcion { get; set; }
        public System.DateTime d_Diagnostico { get; set; }
    
        public virtual Cat_ExpMedico Cat_ExpMedico { get; set; }
        public virtual CM_Medico CM_Medico { get; set; }
    }
}
