//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heredo_familiar
    {
        public int i_pk_heredo_famili { get; set; }
        public string vc_piel { get; set; }
        public string vc_aparato_respiratorio { get; set; }
        public string vc_aparato_digestivo { get; set; }
        public string vc_aparato_geneto_urinario { get; set; }
        public string vc_sistema_nervioso { get; set; }
        public string vc_sistema_musco_esque { get; set; }
        public string vc_sistema_endocrino { get; set; }
        public string vc_sistema_cardio { get; set; }
        public string vc_alergias { get; set; }
        public string vc_cancer { get; set; }
        public string vc_problemas_psicosomaticos { get; set; }
        public string vc_padecimiento_actual { get; set; }
        public int i_pk_estado { get; set; }
    }
}
