//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heredo_familiar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Heredo_familiar()
        {
            this.Exp_Medico = new HashSet<Exp_Medico>();
            this.Exp_Medico1 = new HashSet<Exp_Medico>();
        }
    
        public int i_pk_heredo_famili { get; set; }
        public string vc_piel { get; set; }
        public string vc_aparato_respiratorio { get; set; }
        public string vc_aparato_digestivo { get; set; }
        public string vc_aparato_geneto_urinario { get; set; }
        public string vc_sistema_nervioso { get; set; }
        public string vc_sistema_musco_esque { get; set; }
        public string vc_sistema_endocrino { get; set; }
        public string vc_sistema_cardio { get; set; }
        public string vc_alergias { get; set; }
        public string vc_cancer { get; set; }
        public string vc_problemas_psicosomaticos { get; set; }
        public string vc_padecimiento_actual { get; set; }
        public int i_fk_estado { get; set; }
    
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exp_Medico> Exp_Medico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exp_Medico> Exp_Medico1 { get; set; }
    }
}
