//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_Medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Med_Medico()
        {
            this.Ci_Cita = new HashSet<Ci_Cita>();
        }
    
        public string vc_id_medico { get; set; }
        public string vc_Nombre_Medico { get; set; }
        public string vc_Primer_Apellido { get; set; }
        public string vc_Segundo_Apellido { get; set; }
        public string vc_Especialidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ci_Cita> Ci_Cita { get; set; }
    }
}
