//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_Medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Med_Medico()
        {
            this.Exp_Medico = new HashSet<Exp_Medico>();
        }
    
        public int i_pk_id_medico { get; set; }
        public string vc_Nombre_medico { get; set; }
        public string vc_primer_apellido { get; set; }
        public string vc_segundo_apellido { get; set; }
        public string vc_Especialidad { get; set; }
        public System.DateTime dt_turno_inicio { get; set; }
        public System.DateTime dt_turno_fin { get; set; }
        public int i_fk_estado { get; set; }
        public int i_pk_turno_id { get; set; }
    
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exp_Medico> Exp_Medico { get; set; }
    }
}
