//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaTrabajo> AreaTrabajo { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Cat_Especialidad> Cat_Especialidad { get; set; }
        public virtual DbSet<Cat_EstadoCita> Cat_EstadoCita { get; set; }
        public virtual DbSet<Cat_ExcepHorario> Cat_ExcepHorario { get; set; }
        public virtual DbSet<Cat_ExpMedico> Cat_ExpMedico { get; set; }
        public virtual DbSet<Cat_HorarioServicio> Cat_HorarioServicio { get; set; }
        public virtual DbSet<CategoriaNombramiento> CategoriaNombramiento { get; set; }
        public virtual DbSet<CategoriaPresupuesto> CategoriaPresupuesto { get; set; }
        public virtual DbSet<CM_Cita> CM_Cita { get; set; }
        public virtual DbSet<CM_Medico> CM_Medico { get; set; }
        public virtual DbSet<CM_UsuarioExterno> CM_UsuarioExterno { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<EstadoCivil> EstadoCivil { get; set; }
        public virtual DbSet<Exp_AnteQuirurTrauma> Exp_AnteQuirurTrauma { get; set; }
        public virtual DbSet<Exp_AntPersoPatolog> Exp_AntPersoPatolog { get; set; }
        public virtual DbSet<Exp_Diagnostico> Exp_Diagnostico { get; set; }
        public virtual DbSet<Exp_GinecoObstreticos> Exp_GinecoObstreticos { get; set; }
        public virtual DbSet<Exp_HeredoFamiliar> Exp_HeredoFamiliar { get; set; }
        public virtual DbSet<Funcionarios> Funcionarios { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<SubEspecialidad> SubEspecialidad { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoFuncionario> TipoFuncionario { get; set; }
    }
}
