//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<antecd_quirur_traumati> antecd_quirur_traumati { get; set; }
        public virtual DbSet<Cita> Cita { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Exp_Medico> Exp_Medico { get; set; }
        public virtual DbSet<Gineco_Obstreticos> Gineco_Obstreticos { get; set; }
        public virtual DbSet<Personales_Patologico> Personales_Patologico { get; set; }
        public virtual DbSet<Us_UsuarioExterno> Us_UsuarioExterno { get; set; }
        public virtual DbSet<Ant_pers_patologicos> Ant_pers_patologicos { get; set; }
        public virtual DbSet<Heredo_familiar> Heredo_familiar { get; set; }
    }
}
