//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personales_Patologico
    {
        public string i_pk_antecents_patologicos { get; set; }
        public string vc_piel { get; set; }
        public string vc_aparato_resp { get; set; }
        public string vc_aparato_digestivo { get; set; }
        public string vc_aparato_geneto_U { get; set; }
        public string vc_sistema_nervioso { get; set; }
        public string vc_sistema_musc_esquele { get; set; }
        public string vc_sistema_endocrinolo { get; set; }
        public string vc_sistema_cariodv { get; set; }
        public string vc_alergias { get; set; }
        public string vc_proble_psicologicos { get; set; }
        public int i_pk_estado { get; set; }
    }
}
