//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Us_UsuarioExterno
    {
        public int i_PK_id_usuario { get; set; }
        public string vc_nombre { get; set; }
        public string vc_apellido1 { get; set; }
        public string vc_apellido2 { get; set; }
        public string vc_direccion { get; set; }
        public string vc_telefono { get; set; }
        public System.DateTime dt_nacimiento { get; set; }
        public string vc_sexo { get; set; }
        public string vc_email { get; set; }
        public string vc_puesto { get; set; }
        public int i_pk_estado { get; set; }
    }
}
