//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Us_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Us_Usuario()
        {
            this.Ci_Cita = new HashSet<Ci_Cita>();
            this.Diag_Diagnostico = new HashSet<Diag_Diagnostico>();
            this.Ex_Examen_Diagnostico = new HashSet<Ex_Examen_Diagnostico>();
            this.Exp_Expediente = new HashSet<Exp_Expediente>();
            this.Fnc_Funcion = new HashSet<Fnc_Funcion>();
        }
    
        public string vc_Pk_id_usuario { get; set; }
        public string vc_clave { get; set; }
        public string vc_nombre { get; set; }
        public string vc_apellido { get; set; }
        public string vc_direccion { get; set; }
        public string vc_telefono { get; set; }
        public System.DateTime dt_nacimiento { get; set; }
        public string c_sexo { get; set; }
        public string vc_email { get; set; }
        public string vc_id_puesto { get; set; }
        public string vc_estado_civil { get; set; }
        public string vc_padre { get; set; }
        public string vc_madre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ci_Cita> Ci_Cita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diag_Diagnostico> Diag_Diagnostico { get; set; }
        public virtual Emp_Puesto Emp_Puesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ex_Examen_Diagnostico> Ex_Examen_Diagnostico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exp_Expediente> Exp_Expediente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fnc_Funcion> Fnc_Funcion { get; set; }
    }
}
